### ISSUE TITLE
division by zero

### ISSUE THREAD

**Issue by mgrankin** [kingoflolz/mesh-transformer-jax#95]
if `gradient_accumulation_steps == 1` there is division by zero when calculating `G_noise` and `S_noise`

https://github.com/kingoflolz/mesh-transformer-jax/blob/22de86e3cabb995ad1005cd90b6a407c0a5f954f/device_train.py#L351

**Comment by nostalgebraist** [comment]
> if `gradient_accumulation_steps == 1` there is division by zero when calculating `G_noise` and `S_noise`
> 
> https://github.com/kingoflolz/mesh-transformer-jax/blob/22de86e3cabb995ad1005cd90b6a407c0a5f954f/device_train.py#L351

Thanks for pointing this out.

On a TPU v3-8, `gradient_accumulation_steps == 1 ` is a batch size of 1.  We can't compute gradient noise scale metrics with a batch size of 1, but we should probably warn the user and skip trying to compute them, instead of crashing.

I'm curious -- do have a specific use case where you want to train with a batch size of 1?  I didn't anticipate the issue because I always use larger batches.

(Sidenote: it would be clearer if the code here didn't assume `gradient_accumulation_steps` is equal to the batch size.  Even though they happen to be equal on single TPUs, and `device_train.py` doesn't work on TPU pods.)

**Comment by mgrankin** [comment]
Thank you for a detailed answer. I believe the real batch size is 

```sequences_per_step = gradient_accumulation_steps * (per_replica_batch * tpu_size // cores_per_replica)```

I use `per_replica_batch` as a batch size (and `gradient_accumulation_steps == 1`) for rapid prototyping with small models on a single TPU. Is there any reason not to use `per_replica_batch > 1` and use `gradient_accumulation_steps ` instead?

**Comment by kingoflolz** [comment]
I've found with the v1 model that per_replica_batch==1 and gradient_accumulation_steps==batch is faster than the other way around

**Comment by nostalgebraist** [comment]
To clarify the difference:

- `per_replica_batch`: how many sequences we feed into the model in parallel.  Higher values require more memory 

-  `gradient_accumulation_steps`: how many times we feed data into the model before updating weights.  This happens serially, higher values don't need more memory

The different effects happen through the two different elements of the `batch_size` arg below:

https://github.com/kingoflolz/mesh-transformer-jax/blob/22de86e3cabb995ad1005cd90b6a407c0a5f954f/device_train.py#L236-L239

**Comment by mgrankin** [comment]
Wow, that's contrintuitive. Sequental beats batched. Apparentely, XLA makes great optimizations. Thank you for clarification.

**Comment by kingoflolz** [comment]
Well, I think in this case its more that the batched case hits some edge case which makes it slower, as usually batched should be faster xP

**Comment by mgrankin** [comment]
This sounds like a bug to me then. Should be submitted to JAX/XLA?
